// AUTO-GENERATED by scripts/normalize-logos.mjs — do not edit by hand.
// Source of truth: scripts/logos.json + scripts/logo-sources/*.png
// Regenerate with: npm run logos
//
// Every logo has been background-stripped to transparent and baked to one
// optical weight on a common height, so the strip renders as a single even
// ink tone with no standouts. w/h are each file's intrinsic pixel size.
export const clients = [
  {
    name: "LTHMI",
    logo: "/assets/trusted-by/lthmi.png",
    w: 222,
    h: 200,
  },
  {
    name: "Rapido Motorsiklo Garage",
    logo: "/assets/trusted-by/rapido-motorsiklo-garage.png",
    w: 251,
    h: 200,
  },
  {
    name: "Richmond Square",
    logo: "/assets/trusted-by/richmond-square.png",
    w: 217,
    h: 200,
  },
  {
    name: "Lugaw Juan",
    logo: "/assets/trusted-by/lugawjuan.png",
    w: 192,
    h: 200,
  },
  {
    name: "Topwin",
    logo: "/assets/trusted-by/topwin.png",
    w: 202,
    h: 200,
  },
  {
    name: "RCDC Property Management",
    logo: "/assets/trusted-by/rcdc.png",
    w: 352,
    h: 200,
  },
] as const;
